# basic options
title: Lab 2
author: GitHub User
email: nicholas_lerma@tamu.edu
description: Welcome! Get to know us!
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
